version: '3.9'
services:
  minio:
    image: quay.io/minio/minio  # Official MinIO image
    command: server /data --console-address ":9001"  # Start MinIO server
    environment:
      MINIO_ROOT_USER: root  # Your root user
      MINIO_ROOT_PASSWORD: root-password  # Set a strong password for the root user
      MINIO_ACCESS_KEY: test-s3  # Access key for 'test-s3' user
      MINIO_SECRET_KEY: testing123  # Secret key for 'test-s3' user
    volumes:
      - minio-data:/data  # Persistent data volume
    ports:
      - "9000:9000"  # Expose MinIO web interface
      - "9001:9001"  # Expose MinIO console

volumes:
  minio-data:  # Named volume for persistence
